apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: $KUBERNETES_NAME
  namespace: $KUBERNETES_NAMESPACE
  labels:
    app: $KUBERNETES_NAME
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: $KUBERNETES_NAME
  minReplicas: $KUBERNETES_MIN_REPLICAS
  maxReplicas: $KUBERNETES_MAX_REPLICAS
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: $TARGET_CPU_UTILIZATION_PERCENTAGE